# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('a_id', models.IntegerField(db_column='A_Id', primary_key=True, serialize=False)),
                ('a_title', models.CharField(blank=True, db_column='A_title', max_length=20, null=True)),
                ('isSee', models.BooleanField(db_column='isSee')),
                ('a_url', models.TextField(blank=True, db_column='A_URL', null=True)),
                ('a_type', models.CharField(blank=True, db_column='A_type', max_length=20, null=True)),
                ('a_time', models.DateField(blank=True, db_column='A_time', null=True)),
                ('a_reading_amount', models.BigIntegerField(blank=True, db_column='A_reading_amount', null=True)),
            ],
            options={
                'db_table': 'Article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roletable',
            fields=[
                ('r_id', models.IntegerField(db_column='R_Id', primary_key=True, serialize=False)),
                ('r_type', models.CharField(blank=True, db_column='R_type', max_length=10, null=True)),
            ],
            options={
                'db_table': 'RoleTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('g_id', models.IntegerField(db_column='G_Id', primary_key=True, serialize=False)),
                ('g_name', models.CharField(blank=True, db_column='G_Name', max_length=10, null=True)),
            ],
            options={
                'db_table': 'UserGroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('u_id', models.IntegerField(db_column='U_Id', primary_key=True, serialize=False)),
                ('u_account', models.CharField(blank=True, db_column='U_account', max_length=16, null=True)),
                ('u_password', models.CharField(blank=True, db_column='U_password', max_length=16, null=True)),
                ('u_nickname', models.CharField(blank=True, db_column='U_nickname', max_length=12, null=True)),
                ('u_score', models.IntegerField(blank=True, db_column='U_score', null=True)),
            ],
            options={
                'db_table': 'UserTable',
                'managed': False,
            },
        ),
    ]
